config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show] do
    resources :friendships, only: [:create, :destroy] do
      member do
        post 'decline'
        post 'confirm'
      end
    end
  end
  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorSocialScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="nav">
      <%= link_to 'Stay in touch', root_path %>
      <div class="menu">
        <div class="menu-item">
          <%= menu_link_to 'Timeline', posts_path %>
        </div>
        <div class="menu-item">
          <%= menu_link_to 'All users', users_path %>
        </div>
      </div>
      <% if current_user %>
        <div class="right-menu-item">
          <%= link_to current_user.name, user_path(current_user.id) %>
        </div>
        <div class="right-menu-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
        <%= link_to 'Sign in', user_session_path %>
      <% end %>
    </nav>
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>